### ISSUE TITLE
Clean up references to libcurl

### ISSUE THREAD

**Issue by zcsteele** [steelewool/iraf-v216#10]
There are multiple copies & links for the Curl libraries (the repository contains the source from curl-7.20.1):
```
include/curl			--> vendor/voclient/common/curl/include/curl
vendor/voclient/common/curl	--> vendor/voclient/common/curl-7.20.1
				(contains include/curl with header files)
vendor/voclient/include/curl	(contains duplicated
```
The code should be updated to reference the curl libraries & headers from a single point.  Consider leveraging the OS in a similar fashion to cfitsio (`pkg-config --cflags cfitsio`).

**Comment by RobSteele49** [comment]
Given the latest commit for Obe this is no longer an issue.
