### ISSUE TITLE
xx_votools failure

### ISSUE THREAD

**Issue by RobSteele49** [steelewool/iraf-v216#16]
In my branch oleboleUpdates, which is intended to include all of @olebole (s) pull requests, when I run make sysgen is terminating with:

xc -Nz   -/g -/m64 -p vo -p noao x_votools.o libpkg.a -lasttools -lxtools -lstg -lds -ltbtables -lslalib -o xx_votools.e
/home/steele/git/iraf-v216//bin.linux64/libVO.a(votget.o): In function `votableHandler':
/home/steele/git/iraf-v216/vendor/voclient/voapps/votget.c:343: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
move `xx_votools.e' to `vobin$x_votools.e'

Start:  Mon May  8 12:43:53 PDT 2017
  End:  Mon May  8 12:59:42 PDT 2017

Mon May  8 12:59:42 PDT 2017

Any thoughts as to what might be wrong? Of course I misread that last line which is moving xx_*.e to x_*.e. I was looking for the xx_*.e file, which doesn't exists so I'm assuming this is the correct way the build should end.

**Comment by olebole** [comment]
fixed by iraf/iraf-v216#46

**Comment by olebole** [comment]
BTW, please take into account that I update the PRs from time to time until they get merged, so just merging them once may cause problems.

**Comment by zcsteele** [comment]
I won't be in a position to test the fix until late this evening; @RobSteele49 can you try rebuilding with the latest merge?

**Comment by olebole** [comment]
Just enable travis-CI and it will do the testing for you :-)

**Comment by RobSteele49** [comment]
I'll enable travis-Cl later tonight.

**Comment by RobSteele49** [comment]
I've been updating my oleboleUpdate branch with you latest PRs and things have been looking pretty good.
