### ISSUE TITLE
origin/oleboleUpdates did not build

### ISSUE THREAD

**Issue by RobSteele49** [steelewool/iraf-v216#33]
The last few lines from the build were:
`
Warning, mkpkg line 14: module `libpkg.a' not found or returned error
xc -c -w -/g -/m64 -p vo -p noao x_votools.x
x_votools.x:
Fatal compiler error: Cannot execute xpp.e
HSI is compiled NOVOS
HSI is compiled NOVOS
HSI is compiled NOVOS
HSI is compiled NOVOS
x_votools.r: cant open
HSI is compiled NOVOS
HSI is compiled NOVOS
xc -Nz   -/g -/m64 -p vo -p noao x_votools.o libpkg.a -lasttools -lxtools -lstg -lds -ltbtables -lslalib -o xx_votools.e
Warning: file `x_votools.o' not found
Warning: file `libpkg.a' not found
gcc: error: libex.a: No such file or directory
gcc: error: libsys.a: No such file or directory
gcc: error: libVO.a: No such file or directory
HSI is compiled NOVOS
HSI is compiled NOVOS
Warning, mkpkg line 7: module `relink' not found or returned error
move `xx_votools.e' to `vobin$x_votools.e'
$move: file `xx_votools.e' not found
Warning, mkpkg line 20: error moving file xx_votools.e
Warning, mkpkg line 8: module `install' not found or returned error
Warning, mkpkg line 10: module `update@votools' not found or returned error
Warning, mkpkg line 3: module `update' not found or returned error
'

Start:  Sun May 21 15:51:41 PDT 2017
  End:  Sun May 21 15:55:43 PDT 2017

Sun May 21 15:55:43 PDT 2017

I've attached the spool and spool.final (with .txt attached to the names). Curious if you are getting the same results?

[spool.txt](https://github.com/steelewool/iraf-v216/files/1017420/spool.txt)
[spool.final.txt](https://github.com/steelewool/iraf-v216/files/1017421/spool.final.txt)

**Comment by steelewool** [comment]
With the changes from Ole this has been resolved. I'm closing this item since I don't see this problem any longer.
