### ISSUE TITLE
alloc.e disappearing in build

### ISSUE THREAD

**Issue by RobSteele49** [steelewool/iraf-v216#38]
The following lines are in the output from the build (make sysgen | tee fileName). I'm not understanding what the chmod 4755 is supposed to do. But, it seems to be taking a perfectly good file and turning into an unresolved link. Any thougths?

> gcc -c -I/home/steele/.iraf/ -g -DLINUX -DREDHAT -DPOSIX -DSYSV -DLINUX64 -DMACH64 -Wall -m64 -Wall alloc.c getproc.c
> gcc -I/home/steele/.iraf/ -m64 -Wall alloc.o getproc.o -o alloc.e
> chmod 4755 alloc.e
> mv -f alloc.e ../hlib
> rm -f alloc.o

**Comment by RobSteele49** [comment]
I just removed the 'chmod' from the files mk mkpkg and mkpkg.sh in /unix/os and alloc.* appears to be getting build correctly. Need a little more discussion with Zach before I send any notices to Ole.

**Comment by RobSteele49** [comment]
The commit 7ce1e80b57706224c7b49030510594b9eb5029a8 includes this change.

**Comment by RobSteele49** [comment]
@olebole My build wasn't able to build the file alloc.e correctly until I removed the chmod 4255. I just removed that line in mk mkpkg and mkpkg.sh in unix/os. I'm not even sure why IRAF was using this chmod command. Maybe you have some idea as why.

**Comment by olebole** [comment]
You can just remove it, since it does not what it should. See http://iraf.net/forum/viewtopic.php?showtopic=75130 for the reason of the `chmod`.
The point here is that the file is to be owned by root, with the setuid bit set. However, since the compilation is done as an ordinary user, setting this bit has not the expected effect. `alloc.e` is used anyway for tape drives only, which is not really in use today. If one still needs it, the `chmod` should be done in installation time (in `install -s` as root or so).

**Comment by RobSteele49** [comment]
Based on the iraf forum post and Ole's reply I'm going to back out my change in the merge-all branch and we can just live with this file not being created. I'm still waiting on a reply from @olebole about the build.

**Comment by olebole** [comment]
I don't see what I shall comment here? What is wrong?
On my system, `alloc.e` is build nicely:
```
$ find . -name alloc.e
./unix/bin.linux64/alloc.e
$ ls -l ./unix/bin.linux64/alloc.e
-rwsr-xr-x 1 ole ole 20784 Mai 30 08:46 ./unix/bin.linux64/alloc.e
```

**Comment by RobSteele49** [comment]
Right you are it does build - but one just has to be root to execute it. I guess that meets the design. My other outstanding question for @olebole is on obs.f.

Since I don't have any magnetic tape or drives I doubt if I would ever run this function.
