### ISSUE TITLE
Run Test Results on Raspberry Pi

### ISSUE THREAD

**Issue by steelewool** [steelewool/iraf-v216#48]
On 11/15/17 I ran run_test on my latest version, the results were that two tests reported as having failed. As a side bar the 2nd test inthe images.immatch test also failed on my linux 64 bit machine. Any thoughts @olebole or @zcsteele 

./run_tests 
ecl.e: README.md ...xsa
ecl.e: files.md ......
ecl.e: images.imcoords.md ...........
ecl.e: images.imfilter.md ..............
ecl.e: images.imfit.md ...
ecl.e: images.imgeom.md ........
ecl.e: images.immatch.md .x.
ecl.e: lists.md .......
ecl.e: nttools.md ..............
ecl.e: numerical-recipes.md ..........
ecl.e: programming.md .........
ecl.e: testproc.md ........................
Test summary:    111 passed, 2 skipped, 2 xfailed

**Comment by olebole** [comment]
They are reported as **x**failed, which means: "e**x**pected **fail**ure". Check [`tests/README.md`](https://github.com/steelewool/iraf-v216/blob/ee90954e579044ae02bb6975833267d236e6255c/test/README.md) for how the tests work.

You also can just look into the test files (f.e. [`images.immatch.md`](https://github.com/olebole/iraf-v216/blob/36ba698d688bd72cd50799f67acd3b3cd7947bf3/test/images.immatch.md)) to see the specific test.

**Comment by steelewool** [comment]
Thanks for the clarification. It’s good to have the tests working from both
platforms.

**Comment by steelewool** [comment]
as Ole pointed out, these two tests were expected to fail. So I'm closing this issue.
