### ISSUE TITLE
Which branch from @joequant (iraf or iraf-v216)

### ISSUE THREAD

**Issue by RobSteele49** [steelewool/iraf-v216#8]
@zcsteele which repository did you use of @joequant?

**Comment by zcsteele** [comment]
@joequant has a branch named [iraf-v216](https://github.com/joequant/iraf-v216) forked from the official iraf-v216 repository.  Any pull requests should reference that branch.

**Comment by RobSteele49** [comment]
That is what I thought you had done - but I wanted to check.
