### ISSUE TITLE
In the updateMakefiles branch I found an incorrect softlink

### ISSUE THREAD

**Issue by steelewool** [steelewool/iraf-v216#9]
The directory noaolib doesn't exist. the softlink should be referencing noao/lib. Not sure where this error is coming from.

steele@steele-VirtualBox:~/git/iraf-v216/noao/astutil$ ls -lt libasttools.a 
lrwxrwxrwx 1 steele steele 21 May  1 08:26 libasttools.a -> noaolib/libasttools.a

**Comment by RobSteele49** [comment]
problem has been resolved.
